version: 2
mergeable:
  - when: pull_request.ready_for_review
    name: "Test vote pull_request.ready_for_review"
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
    pass:
      - do: checks
        status: 'success'
        payload:
          title: 'Mergeable: pull_request.ready_for_review'
          summary: "All the validators have returned 'pass'!"

  - when: pull_request.labeled
    name: "Test vote pull_request.labeled"
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
    pass:
      - do: checks
        status: 'success'
        payload:
          title: 'Mergeable: pull_request.labeled'
          summary: "All the validators have returned 'pass'!"
